version: "2"
services:
  nginx-react:
    container_name: client_lets_cook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production