version: '3'
services:
  lets_cook_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodApp
    ports:
      - "5434:5432"

  lets_cook_api:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./:/app
      # Anonymous volume:
      - /app/node_modules
    depends_on:
      - lets_cook_db